//! Session workloads: chains of requests where each step re-enters with its
//! parent's whole context as prefix plus some novel tokens, after a gap the
//! harness spent between the parent's completion and this arrival (a tool
//! call executing, a user typing).
//!
//! A session file is JSONL, one session per line:
//!
//! ```json
//! {"id": "claude:000adcd5", "steps": [
//!   {"input": 15524, "new": 15524, "output": 111, "gap": 0.0, "kind": "user"},
//!   {"input": 17079, "new": 1444, "output": 96, "gap": 0.104, "kind": "tool"}
//! ]}
//! ```
//!
//! `input` is the step's prompt length, `new` the tokens of it that are not
//! the parent's context (so `input - new` is the reusable prefix), `output`
//! the tokens generated, and `gap` the seconds between the parent's
//! completion and this step's arrival. The step's prefix identity is built
//! from block hashes: the parent's hashes over the shared prefix, then fresh
//! hashes for the novel tail and the step's own output. Hashes cover the
//! output too, so a re-entry hits the parent's generated tokens as well as its
//! prompt.

use super::Request;
use serde::Deserialize;
use std::cmp::Reverse;
use std::collections::{BinaryHeap, HashMap};
use std::io::BufRead;

/// One step of a session, as read from the session file.
#[derive(Debug, Clone, Deserialize, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct StepSpec {
    /// Prompt tokens of this step (the whole context the model sees).
    pub input: u32,
    /// Prompt tokens that are not the parent's context: the novel tail.
    pub new: u32,
    /// Output tokens generated by this step.
    pub output: u32,
    /// Seconds between the parent's completion and this step's arrival.
    /// Ignored on the first step (the session start is set by the arrival
    /// pattern).
    #[serde(default)]
    pub gap: f64,
    /// Free-form step kind (`"user"`, `"tool"`, ...). Carried through for
    /// analysis, not interpreted.
    #[serde(default)]
    pub kind: Option<String>,
}

/// A session: an ordered chain of steps.
#[derive(Debug, Clone, Deserialize, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct SessionSpec {
    pub id: String,
    pub steps: Vec<StepSpec>,
}

impl SessionSpec {
    /// Read sessions from JSONL. Sessions with no steps are dropped.
    pub fn read_jsonl<R: BufRead>(reader: R) -> Result<Vec<SessionSpec>, String> {
        let mut out = Vec::new();
        for (i, line) in reader.lines().enumerate() {
            let line = line.map_err(|e| format!("line {}: {e}", i + 1))?;
            if line.trim().is_empty() {
                continue;
            }
            let spec: SessionSpec =
                serde_json::from_str(&line).map_err(|e| format!("line {}: {e}", i + 1))?;
            if !spec.steps.is_empty() {
                out.push(spec);
            }
        }
        Ok(out)
    }

    /// Load a session file from disk.
    pub fn load(path: &str) -> Result<Vec<SessionSpec>, String> {
        let file = std::fs::File::open(path).map_err(|e| format!("{path}: {e}"))?;
        Self::read_jsonl(std::io::BufReader::new(file))
            .map_err(|e| format!("{path}: {e}"))
            .and_then(|sessions| {
                if sessions.is_empty() {
                    Err(format!("{path}: no sessions"))
                } else {
                    Ok(sessions)
                }
            })
    }
}

/// Which session step a request is, stamped on the [`Request`] so metrics
/// can attribute it. `session` is the run's session ordinal (the n-th session
/// started), not an index into the file.
#[derive(Debug, Clone, PartialEq)]
pub struct SessionStep {
    pub session: u32,
    pub step: u32,
    /// Seconds between the parent's completion and this arrival (0 for the
    /// first step).
    pub gap: f64,
    /// Prompt tokens shared with the parent's context (0 for the first step).
    pub shared_tokens: u32,
    pub kind: Option<String>,
    /// KV bytes the engine had written when the parent completed (set by the
    /// driver), and the bytes written between then and this request's
    /// arrival at the engine (set by the engine): the reuse distance. The
    /// `touched` pair also counts hits that pulled free blocks back into
    /// use; written and touched bracket the LRU stack distance.
    pub parent_bytes_written: Option<u64>,
    pub reuse_distance_bytes: Option<u64>,
    pub parent_bytes_touched: Option<u64>,
    pub reuse_touched_bytes: Option<u64>,
    /// The session's next step, if any: the harness gap after this step's
    /// completion, and how many of this step's context tokens (prompt +
    /// output, whole blocks) it re-enters with. What an oracle knows.
    pub next_gap: Option<f64>,
    pub next_shared_tokens: u32,
}

impl SessionStep {
    /// The re-entry this step announces, given its completion time.
    pub fn outlook_at(&self, completion_time: f64) -> Option<Outlook> {
        self.next_gap.map(|gap| Outlook {
            next_arrival: completion_time + gap.max(0.0),
            shared_tokens: self.next_shared_tokens,
        })
    }
}

/// A session's announced re-entry: when its next step arrives and how many
/// tokens of the current context it reuses. Oracle policies read it;
/// reactive ones never see it.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct Outlook {
    pub next_arrival: f64,
    pub shared_tokens: u32,
}

/// State of a session that has started and not yet issued its last step.
struct ActiveSession {
    spec_idx: usize,
    /// Step to issue next.
    next_step: usize,
    /// Block hashes of the parent's whole sequence (prompt + output).
    hashes: Vec<u64>,
    /// Parent's context length in tokens (prompt + output).
    context_tokens: u32,
}

/// Turns session specs into requests: starts sessions on demand, queues each
/// step at its parent's completion plus gap, and builds prefix identities.
pub struct SessionSource {
    specs: Vec<SessionSpec>,
    block_size: u32,
    /// Next spec to start (cycles through the file).
    next_spec: usize,
    /// Sessions started so far; also the ordinal stamped on their requests.
    started: u32,
    active: HashMap<u32, ActiveSession>,
    /// Steps due: (arrival time, session ordinal), earliest first.
    pending: BinaryHeap<Reverse<(OrderedTime, u32)>>,
    next_hash: u64,
}

/// f64 wrapper ordered by value so it can sit in a heap key. Times are
/// finite by construction.
#[derive(Debug, Clone, Copy, PartialEq)]
struct OrderedTime(f64);
impl Eq for OrderedTime {}
impl PartialOrd for OrderedTime {
    fn partial_cmp(&self, other: &Self) -> Option<std::cmp::Ordering> {
        Some(self.cmp(other))
    }
}
impl Ord for OrderedTime {
    fn cmp(&self, other: &Self) -> std::cmp::Ordering {
        self.0.total_cmp(&other.0)
    }
}

impl SessionSource {
    pub fn new(specs: Vec<SessionSpec>, block_size: u32) -> Self {
        Self {
            specs,
            block_size: block_size.max(1),
            next_spec: 0,
            started: 0,
            active: HashMap::new(),
            pending: BinaryHeap::new(),
            // Fresh hashes are drawn from a counter; start high so they
            // cannot collide with small literal hashes used elsewhere.
            next_hash: 1 << 40,
        }
    }

    /// Sessions in the file.
    pub fn num_specs(&self) -> usize {
        self.specs.len()
    }

    /// Sessions started so far.
    pub fn num_started(&self) -> u32 {
        self.started
    }

    /// Sessions that have started and still have steps to issue or in flight.
    pub fn num_active(&self) -> usize {
        self.active.len()
    }

    /// Earliest queued step arrival, if any.
    pub fn peek_pending(&self) -> Option<f64> {
        self.pending.peek().map(|Reverse((t, _))| t.0)
    }

    /// Whether a queued step is due at or before `current_time`.
    pub fn has_due(&self, current_time: f64) -> bool {
        self.peek_pending().is_some_and(|t| t <= current_time)
    }

    /// Start the next session at `arrival_time` and return its first step.
    pub fn start_session(&mut self, arrival_time: f64) -> Request {
        let spec_idx = self.next_spec;
        self.next_spec = (self.next_spec + 1) % self.specs.len();
        let ordinal = self.started;
        self.started += 1;
        self.active.insert(
            ordinal,
            ActiveSession {
                spec_idx,
                next_step: 0,
                hashes: Vec::new(),
                context_tokens: 0,
            },
        );
        self.issue_step(ordinal, arrival_time, 0.0)
    }

    /// Pop the earliest queued step if it is due by `current_time`.
    pub fn next_due(&mut self, current_time: f64) -> Option<Request> {
        let Reverse((t, ordinal)) = *self.pending.peek()?;
        if t.0 > current_time {
            return None;
        }
        self.pending.pop();
        let active = &self.active[&ordinal];
        let gap = self.specs[active.spec_idx].steps[active.next_step]
            .gap
            .max(0.0);
        Some(self.issue_step(ordinal, t.0, gap))
    }

    /// A step completed at `completion_time`: queue the session's next step
    /// at `completion_time + gap`. Returns `true` if a step was queued, and
    /// `false` if the session is over (it is retired here).
    pub fn on_step_complete(&mut self, step: &SessionStep, completion_time: f64) -> bool {
        let Some(active) = self.active.get(&step.session) else {
            return false;
        };
        let spec = &self.specs[active.spec_idx];
        if active.next_step >= spec.steps.len() {
            self.active.remove(&step.session);
            return false;
        }
        let gap = spec.steps[active.next_step].gap.max(0.0);
        self.pending
            .push(Reverse((OrderedTime(completion_time + gap), step.session)));
        true
    }

    fn issue_step(&mut self, ordinal: u32, arrival_time: f64, gap: f64) -> Request {
        let block_size = self.block_size;
        let active = self.active.get_mut(&ordinal).expect("session is active");
        let step_idx = active.next_step;
        let step = &self.specs[active.spec_idx].steps[step_idx];
        let input = step.input.max(1);
        let output = step.output.max(1);

        // Shared prefix: the parent's context minus this step's novel tail,
        // never more than the parent actually had, in whole blocks (a partial
        // block continued with new tokens has new content).
        let shared_tokens = if step_idx == 0 {
            0
        } else {
            input.saturating_sub(step.new).min(active.context_tokens)
        };
        let shared_blocks = (shared_tokens / block_size) as usize;
        let total_blocks = (input + output).div_ceil(block_size) as usize;
        let mut hashes = Vec::with_capacity(total_blocks);
        hashes.extend_from_slice(&active.hashes[..shared_blocks.min(active.hashes.len())]);
        while hashes.len() < total_blocks {
            hashes.push(self.next_hash);
            self.next_hash += 1;
        }

        // What the next step re-enters with, in whole blocks of this
        // step's context.
        let context = input + output;
        let next = self.specs[active.spec_idx].steps.get(step_idx + 1);
        let next_gap = next.map(|n| n.gap.max(0.0));
        let next_shared_tokens = next
            .map(|n| n.input.max(1).saturating_sub(n.new).min(context) / block_size * block_size)
            .unwrap_or(0);

        let mut req = Request::new_with_target(
            format!("s{ordinal}/{step_idx}"),
            0,
            arrival_time,
            input,
            output,
            output,
        );
        req.prompt_block_hashes = hashes.clone();
        req.session = Some(Box::new(SessionStep {
            session: ordinal,
            step: step_idx as u32,
            gap,
            shared_tokens: (shared_blocks as u32) * block_size,
            kind: step.kind.clone(),
            parent_bytes_written: None,
            reuse_distance_bytes: None,
            parent_bytes_touched: None,
            reuse_touched_bytes: None,
            next_gap,
            next_shared_tokens,
        }));

        active.hashes = hashes;
        active.context_tokens = input + output;
        active.next_step += 1;
        req
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn two_step() -> Vec<SessionSpec> {
        vec![SessionSpec {
            id: "s".into(),
            steps: vec![
                StepSpec {
                    input: 100,
                    new: 100,
                    output: 20,
                    gap: 0.0,
                    kind: Some("user".into()),
                },
                StepSpec {
                    input: 130,
                    new: 10,
                    output: 5,
                    gap: 2.5,
                    kind: Some("tool".into()),
                },
            ],
        }]
    }

    #[test]
    fn parses_jsonl_and_drops_empty_sessions() {
        let text = r#"{"id":"a","steps":[{"input":10,"new":10,"output":1}]}

{"id":"b","steps":[]}
"#;
        let specs = SessionSpec::read_jsonl(text.as_bytes()).unwrap();
        assert_eq!(specs.len(), 1);
        assert_eq!(specs[0].id, "a");
        assert_eq!(specs[0].steps[0].gap, 0.0);
        assert!(SessionSpec::read_jsonl("{bad".as_bytes()).is_err());
    }

    #[test]
    fn re_entry_shares_parent_prompt_and_output_hashes() {
        // block 16: step 0 = 100 prompt + 20 output = 120 tokens = 8 blocks.
        // step 1 shares 130 - 10 = 120 tokens = 7 whole blocks (block 7 was
        // partial: 112..120 of 120 tokens... 120/16 = 7 whole blocks).
        let mut src = SessionSource::new(two_step(), 16);
        let first = src.start_session(1.0);
        assert_eq!(first.request_id, "s0/0");
        assert_eq!(first.num_prompt_tokens, 100);
        assert_eq!(first.target_output_tokens, 20);
        assert_eq!(first.prompt_block_hashes.len(), 8);
        let s0 = first.session.clone().unwrap();
        assert_eq!((s0.session, s0.step, s0.shared_tokens), (0, 0, 0));

        assert!(src.next_due(100.0).is_none());
        assert!(src.on_step_complete(&s0, 10.0));
        assert_eq!(src.peek_pending(), Some(12.5));
        assert!(src.next_due(12.4).is_none());
        let second = src.next_due(12.5).unwrap();
        assert_eq!(second.request_id, "s0/1");
        assert_eq!(second.arrival_time, 12.5);
        assert_eq!(second.num_prompt_tokens, 130);
        // 130 + 5 = 135 tokens = 9 blocks; the first 7 are the parent's.
        assert_eq!(second.prompt_block_hashes.len(), 9);
        assert_eq!(
            &second.prompt_block_hashes[..7],
            &first.prompt_block_hashes[..7]
        );
        assert_ne!(second.prompt_block_hashes[7], first.prompt_block_hashes[7]);
        let s1 = second.session.clone().unwrap();
        assert_eq!((s1.step, s1.gap, s1.shared_tokens), (1, 2.5, 112));

        // Last step: completing it retires the session.
        assert!(!src.on_step_complete(&s1, 20.0));
        assert_eq!(src.num_active(), 0);
        assert!(src.peek_pending().is_none());
    }

    #[test]
    fn shared_prefix_is_capped_by_parent_context() {
        let mut specs = two_step();
        specs[0].steps[1].new = 0; // claims 130 shared, parent had 120
        let mut src = SessionSource::new(specs, 16);
        let first = src.start_session(0.0);
        src.on_step_complete(first.session.as_ref().unwrap(), 1.0);
        let second = src.next_due(10.0).unwrap();
        assert_eq!(second.session.unwrap().shared_tokens, 112);
    }

    #[test]
    fn sessions_cycle_through_the_file() {
        let mut src = SessionSource::new(two_step(), 16);
        let a = src.start_session(0.0);
        let b = src.start_session(0.0);
        assert_eq!(a.request_id, "s0/0");
        assert_eq!(b.request_id, "s1/0");
        assert_ne!(a.prompt_block_hashes[0], b.prompt_block_hashes[0]);
        assert_eq!(src.num_started(), 2);
        assert_eq!(src.num_active(), 2);
    }
}
